model:
  bootstrap: true
  ccp_alpha: 0.0
  class_weight: null
  criterion: gini
  max_depth: null
  max_features: auto
  max_leaf_nodes: null
  max_samples: null
  min_impurity_decrease: 0.0
  min_samples_leaf: 1
  min_samples_split: 2
  min_weight_fraction_leaf: 0.0
  n_estimators: 1
  n_jobs: null
  oob_score: false
  random_state: 0
  verbose: 0
  warm_start: false
model_class: RandomForestClassifier
